#pragma once
#define  LOCTEXT_NAMESPACE " ActionGameplayTag"
#include "NativeGameplayTags.h"

namespace  ActionGameplayTags
{
	//在这里定义所有的GameplayTag标签
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move)
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Look)

	//Skill输入
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RelaxAttack)
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyAttack)
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dash)
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Defense)
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PowerAttack)

	//完美闪避
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PerfectSkill)
	//Weapon
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sword)
	BAIGUIZHEN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gun)
	
}
#undef LOCTEXT_NAMESPACE
